import { LessonData, Exercise } from './types';

export const LESSONS: Record<string, LessonData> = {
  '16': {
    id: '16',
    title: 'Lesson 16',
    subtitle: 'Know / Learn',
    vocabulary: [
      { word: 'to fly', translation: 'voar' },
      { word: 'to sing', translation: 'cantar' },
      { word: 'to cook', translation: 'cozinhar' },
      { word: 'to dance', translation: 'dançar' },
      { word: 'to play an instrument', translation: 'tocar um instrumento' },
      { word: 'to paint', translation: 'pintar' },
      { word: 'to draw', translation: 'desenhar' },
      { word: 'to fix a computer', translation: 'consertar um computador' },
      { word: 'to ride a bike', translation: 'andar de bicicleta' },
      { word: 'to read', translation: 'ler' },
      { word: 'to write', translation: 'escrever' },
    ],
    phrases: [
      { text: 'I know how to cook.', translation: 'Eu sei cozinhar.' },
      { text: "I don't know how to dance.", translation: 'Eu não sei dançar.' },
      { text: 'Do you know how to fix a computer?', translation: 'Você sabe consertar um computador?' },
      { text: 'She learns how to paint.', translation: 'Ela aprende a pintar.' },
      { text: "He doesn't learn how to sing.", translation: 'Ele não aprende a cantar.' },
      { text: 'Do they learn how to fly?', translation: 'Eles aprendem a voar?' },
      { text: 'What do you know how to do?', translation: 'O que você sabe fazer?' },
      { text: 'My brother knows how to ride a bike.', translation: 'Meu irmão sabe andar de bicicleta.' },
      { text: "We don't know how to play an instrument.", translation: 'Nós não sabemos tocar um instrumento.' },
    ],
  },
  '17': {
    id: '17',
    title: 'Lesson 17',
    subtitle: 'Travel / Go',
    vocabulary: [
      { word: 'car', translation: 'carro' },
      { word: 'bike', translation: 'bicicleta' },
      { word: 'bus', translation: 'ônibus' },
      { word: 'plane', translation: 'avião' },
      { word: 'truck', translation: 'caminhão' },
      { word: 'train', translation: 'trem' },
      { word: 'helicopter', translation: 'helicóptero' },
      { word: 'subway', translation: 'metrô' },
      { word: 'motorcycle', translation: 'motocicleta' },
      { word: 'ship', translation: 'navio' },
      { word: 'boat', translation: 'barco' },
      { word: 'on foot', translation: 'a pé' },
      { word: 'school', translation: 'escola' },
      { word: 'library', translation: 'biblioteca' },
      { word: 'work', translation: 'trabalho' },
      { word: 'restaurant', translation: 'restaurante' },
      { word: 'abroad', translation: 'exterior' },
    ],
    phrases: [
      { text: 'I am going to travel by plane.', translation: 'Eu vou viajar de avião.' },
      { text: 'She is not going to go by car.', translation: 'Ela não vai de carro.' },
      { text: 'Are you going to go to school?', translation: 'Você vai para a escola?' },
      { text: 'We go to work by bus.', translation: 'Nós vamos para o trabalho de ônibus.' },
      { text: 'They go to the library on foot.', translation: 'Eles vão para a biblioteca a pé.' },
      { text: 'Where are you going to go?', translation: 'Onde você vai?' },
      { text: 'He is going to travel abroad.', translation: 'Ele vai viajar para o exterior.' },
      { text: 'I am not going to go by truck.', translation: 'Eu não vou de caminhão.' },
      { text: 'Are they going to go by train?', translation: 'Eles vão de trem?' },
    ],
  },
  '18': {
    id: '18',
    title: 'Lesson 18',
    subtitle: 'Try / Begin',
    vocabulary: [
      { word: 'T-shirt', translation: 'camiseta' },
      { word: 'coat', translation: 'casaco' },
      { word: 'shoes', translation: 'sapatos' },
      { word: 'again', translation: 'novamente' },
      { word: 'your best', translation: 'seu melhor' },
      { word: 'the show', translation: 'o show' },
      { word: 'to rain', translation: 'chover' },
      { word: 'the project', translation: 'o projeto' },
      { word: 'my day', translation: 'meu dia' },
    ],
    phrases: [
      { text: 'I am going to try on this T-shirt.', translation: 'Eu vou experimentar esta camiseta.' },
      { text: 'She is going to try on that coat.', translation: 'Ela vai experimentar aquele casaco.' },
      { text: 'It is beginning to rain.', translation: 'Está começando a chover.' },
      { text: 'The show begins at eight.', translation: 'O show começa às oito.' },
      { text: 'I try to do my best every day.', translation: 'Eu tento fazer o meu melhor todos os dias.' },
      { text: 'When does the project begin?', translation: 'Quando o projeto começa?' },
      { text: "Don't try to fix it again.", translation: 'Não tente consertar isso novamente.' },
      { text: 'Are you going to try on these shoes?', translation: 'Você vai experimentar estes sapatos?' },
      { text: 'My day begins very early.', translation: 'Meu dia começa muito cedo.' },
    ],
  },
  '19': {
    id: '19',
    title: 'Lesson 19',
    subtitle: 'Modal Should',
    vocabulary: [
      { word: 'to say', translation: 'dizer' },
      { word: 'bad words', translation: 'palavrões' },
      { word: 'swear words', translation: 'xingamentos' },
      { word: 'invite', translation: 'convidar' },
      { word: 'think', translation: 'pensar' },
      { word: 'come', translation: 'vir' },
      { word: 'hurry', translation: 'apressar-se' },
      { word: 'give up', translation: 'desistir' },
      { word: 'leave', translation: 'sair / partir' },
      { word: 'watch out', translation: 'cuidado' },
      { word: 'have studied', translation: 'ter estudado' },
      { word: 'have listened', translation: 'ter escutado' },
      { word: 'hesitate', translation: 'hesitar' },
    ],
    phrases: [
      { text: 'You should say sorry.', translation: 'Você deveria pedir desculpas.' },
      { text: "We shouldn't say bad words.", translation: 'Nós não deveríamos dizer palavrões.' },
      { text: 'Should I invite him?', translation: 'Eu deveria convidá-lo?' },
      { text: 'He should think before he speaks.', translation: 'Ele deveria pensar antes de falar.' },
      { text: 'You should come early.', translation: 'Você deveria vir cedo.' },
      { text: "They shouldn't give up.", translation: 'Eles não deveriam desistir.' },
      { text: 'What should I do?', translation: 'O que eu deveria fazer?' },
      { text: 'When should we leave?', translation: 'Quando deveríamos sair?' },
      { text: 'Where should they go?', translation: 'Onde eles deveriam ir?' },
      { text: 'Why should she hurry?', translation: 'Por que ela deveria se apressar?' },
    ],
  },
  '20': {
    id: '20',
    title: 'Lesson 20',
    subtitle: 'Would Like',
    vocabulary: [
      { word: 'to see', translation: 'ver' },
      { word: 'to order food', translation: 'pedir comida' },
      { word: 'to understand', translation: 'entender' },
      { word: 'to live', translation: 'morar / viver' },
      { word: 'to stay', translation: 'ficar' },
    ],
    phrases: [
      { text: "I'd like to see the menu.", translation: 'Eu gostaria de ver o cardápio.' },
      { text: "I'd like to order now.", translation: 'Eu gostaria de pedir agora.' },
      { text: "I'd like to say something.", translation: 'Eu gostaria de dizer algo.' },
      { text: "I'd like to understand it.", translation: 'Eu gostaria de entender isso.' },
      { text: "I'd like to live abroad.", translation: 'Eu gostaria de morar no exterior.' },
      { text: "I'd like to stay for dinner.", translation: 'Eu gostaria de ficar para o jantar.' },
      { text: "Would you like to order food?", translation: 'Você gostaria de pedir comida?' },
      { text: "She wouldn't like to live here.", translation: 'Ela não gostaria de morar aqui.' },
      { text: "We would like to understand the problem.", translation: 'Nós gostaríamos de entender o problema.' },
    ],
  },
};

// Helper to shuffle array
const shuffle = (array: string[]) => {
  return [...array].sort(() => Math.random() - 0.5);
};

export const EXERCISES: Exercise[] = [
  // --- ORDER EXERCISES (Unchanged) ---
  {
    id: 'l16-o1',
    type: 'order',
    question: 'I know how to cook',
    scrambled: shuffle(['know', 'I', 'to', 'how', 'cook']),
  },
  {
    id: 'l16-o2',
    type: 'order',
    question: 'Do you know how to fix a computer',
    scrambled: shuffle(['know', 'you', 'Do', 'to', 'fix', 'how', 'computer', 'a']),
  },
  {
    id: 'l16-o3',
    type: 'order',
    question: "He doesn't learn how to sing",
    scrambled: shuffle(['He', 'how', 'learn', "doesn't", 'to', 'sing']),
  },
  {
    id: 'l17-o1',
    type: 'order',
    question: 'Where are you going to go',
    scrambled: shuffle(['going', 'are', 'Where', 'to', 'you', 'go']),
  },
  {
    id: 'l17-o2',
    type: 'order',
    question: 'I am not going to go by truck',
    scrambled: shuffle(['truck', 'go', 'to', 'am', 'by', 'going', 'not', 'I']),
  },
  {
    id: 'l17-o3',
    type: 'order',
    question: 'She is not going to go by car',
    scrambled: shuffle(['She', 'to', 'not', 'go', 'is', 'going', 'by', 'car']),
  },
  {
    id: 'l18-o1',
    type: 'order',
    question: 'I am going to try on this T-shirt',
    scrambled: shuffle(['try', 'going', 'to', 'am', 'on', 'I', 'T-shirt', 'this']),
  },
  {
    id: 'l18-o2',
    type: 'order',
    question: 'It is beginning to rain',
    scrambled: shuffle(['rain', 'to', 'beginning', 'is', 'It']),
  },
  {
    id: 'l18-o3',
    type: 'order',
    question: 'When does the project begin',
    scrambled: shuffle(['begin', 'project', 'the', 'does', 'When']),
  },
  {
    id: 'l19-o1',
    type: 'order',
    question: 'You should say sorry',
    scrambled: shuffle(['should', 'sorry', 'say', 'You']),
  },
  {
    id: 'l19-o2',
    type: 'order',
    question: 'Where should they go',
    scrambled: shuffle(['should', 'go', 'Where', 'they']),
  },
  {
    id: 'l19-o3',
    type: 'order',
    question: "We shouldn't say bad words",
    scrambled: shuffle(['say', "shouldn't", 'We', 'bad', 'words']),
  },
  {
    id: 'l20-o1',
    type: 'order',
    question: 'I would like to order now',
    scrambled: shuffle(['like', 'would', 'to', 'order', 'I', 'now']),
  },
  {
    id: 'l20-o2',
    type: 'order',
    question: "She wouldn't like to live here",
    scrambled: shuffle(['like', "wouldn't", 'She', 'to', 'live', 'here']),
  },
  {
    id: 'l20-o3',
    type: 'order',
    question: 'Would you like to order food',
    scrambled: shuffle(['like', 'Would', 'you', 'to', 'order', 'food']),
  },

  // --- COMPLETE EXERCISES (New Type - No Voice) ---
  // Lesson 16
  {
    id: 'l16-c1',
    type: 'complete',
    question: "I _____ how to dance.",
    correctAnswer: "don't know",
    options: ["don't know", "doesn't know", "knowing"],
  },
  {
    id: 'l16-c2',
    type: 'complete',
    question: "She _____ how to paint.",
    correctAnswer: "learns",
    options: ["learn", "learns", "learning"],
  },
  {
    id: 'l16-c3',
    type: 'complete',
    question: "_____ you know how to cook?",
    correctAnswer: "Do",
    options: ["Does", "Do", "Are"],
  },
  // Lesson 17
  {
    id: 'l17-c1',
    type: 'complete',
    question: "We go to work _____ bus.",
    correctAnswer: "by",
    options: ["on", "by", "to"],
  },
  {
    id: 'l17-c2',
    type: 'complete',
    question: "I am _____ to travel by plane.",
    correctAnswer: "going",
    options: ["go", "going", "goes"],
  },
  {
    id: 'l17-c3',
    type: 'complete',
    question: "They go to the library _____ foot.",
    correctAnswer: "on",
    options: ["by", "on", "at"],
  },
  // Lesson 18
  {
    id: 'l18-c1',
    type: 'complete',
    question: "I am going to _____ on this coat.",
    correctAnswer: "try",
    options: ["try", "trying", "tries"],
  },
  {
    id: 'l18-c2',
    type: 'complete',
    question: "The show _____ at eight.",
    correctAnswer: "begins",
    options: ["begin", "begins", "beginning"],
  },
  {
    id: 'l18-c3',
    type: 'complete',
    question: "_____ does the project begin?",
    correctAnswer: "When",
    options: ["What", "When", "Who"],
  },
  // Lesson 19
  {
    id: 'l19-c1',
    type: 'complete',
    question: "You _____ say sorry.",
    correctAnswer: "should",
    options: ["should", "would", "do"],
  },
  {
    id: 'l19-c2',
    type: 'complete',
    question: "We _____ say bad words.",
    correctAnswer: "shouldn't",
    options: ["should", "shouldn't", "don't"],
  },
  {
    id: 'l19-c3',
    type: 'complete',
    question: "_____ should I do?",
    correctAnswer: "What",
    options: ["When", "What", "Where"],
  },
  // Lesson 20
  {
    id: 'l20-c1',
    type: 'complete',
    question: "I _____ like to order now.",
    correctAnswer: "would",
    options: ["will", "would", "do"],
  },
  {
    id: 'l20-c2',
    type: 'complete',
    question: "_____ you like to stay for dinner?",
    correctAnswer: "Would",
    options: ["Do", "Are", "Would"],
  },
  {
    id: 'l20-c3',
    type: 'complete',
    question: "She wouldn't _____ to live here.",
    correctAnswer: "like",
    options: ["likes", "liked", "like"],
  },
];